AppBundle\Entity\Utilisateur:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: email
    properties:
        nom:
            - NotBlank: ~
            - Type: string
        prenom:
            - NotBlank: ~
            - Type: string
        email:
            - NotBlank: ~
            - Type: string
        mot_de_pass:
            - NotBlank: ~
            - Type: string
            
AppBundle\Entity\Album:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: id
    properties:
        titre:
            - NotBlank: ~
            - Type: string
        date_creation:
            - NotBlank: ~
            - Type: string
        uti_id:
            - NotBlank: ~
            - Type: integer
            
AppBundle\Entity\Photo:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: id
    properties:
        titre:
            - NotBlank: ~
            - Type: string
        date_creation:
            - NotBlank: ~
            - Type: string
        legende:
            - NotBlank: ~
            - Type: string
        image:
            - NotBlank: ~
            - File : 
        alb_id:
            - NotBlank: ~
            - Type: integer
        uti_id:
            - NotBlank: ~
            - Type: integer
     
AppBundle\Entity\Ami:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: id
    properties:
        uti_id:
            - NotBlank: ~
            - Type: integer
        ami_id:
            - NotBlank: ~
            - Type: integer
            
AppBundle\Entity\AlbumPartage:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: id
    properties:
        uti_id:
            - NotBlank: ~
            - Type: integer
        alb_id:
            - NotBlank: ~
            - Type: integer
